export const CENTIMETERS_PER_UNIT = 10;
export const MILLIMETERS_PER_UNIT = 100;
export const METERS_PER_UNIT = 0.1;
export const METERS_PER_CENTIMETER = METERS_PER_UNIT / CENTIMETERS_PER_UNIT;
export const METERS_PER_MILLIMETER = METERS_PER_UNIT / MILLIMETERS_PER_UNIT;

export const UNIT_SCALE_DESCRIPTION = '1 unit = 10 cm; 1c = 1 cm; 1m = 1 mm';
